# Generated by Django 4.0.1 on 2025-06-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
